/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyTableComponent {
    }
}
declare global {
    interface HTMLMyTableComponentElement extends Components.MyTableComponent, HTMLStencilElement {
    }
    var HTMLMyTableComponentElement: {
        prototype: HTMLMyTableComponentElement;
        new (): HTMLMyTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-table-component": HTMLMyTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyTableComponent {
    }
    interface IntrinsicElements {
        "my-table-component": MyTableComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-table-component": LocalJSX.MyTableComponent & JSXBase.HTMLAttributes<HTMLMyTableComponentElement>;
        }
    }
}
